# Generated by Django 3.0.7 on 2021-07-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('facebook_link', models.URLField(max_length=100)),
                ('twittter_link', models.URLField(max_length=100)),
                ('google_plust_link', models.URLField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
