# Generated by Django 3.0.7 on 2021-07-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210717_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name': ' Auto', 'verbose_name_plural': 'Autos'},
        ),
    ]
